name: PR workflow

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
    branches: [ develop, v*, main ]

  permissions:
    pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Flutter Install
        uses: ./github/actions/install

      - name: Flutter Analyzer
        uses: ./github/actions/analyze
