name: PR Workflow

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [develop, v*, main]

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # - name: Install Flutter
      #   uses: ./github/actions/install
      #   with:
      #     flutter-version: stable

      # - name: Run Flutter Analyzer
      #   uses: ./github/actions/analyze
