name: Deploy to Firebase Hosting on merge
description: Deploy to Firebase Hosting on merge
runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_VAULTARIUM_A4359 }}
          channelId: live
          projectId: vaultarium-a4359
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks